package sg.com.ioutlet.framework.web;

public enum WebConstants {
	FORM_LOAD_DATE, 
	FORM_OBJECT, 
	LOGGED_IN_USER,
	LOGGED_IN_USER_INFO,
	LOGGED_IN_AT_OTHER_SESSION,
	RELOAD_USER,
	USER_DOMAIN_FUNCTIONS,
	USER_REGISTRY_MAP,
	SESSION_ID,
	ERROR_SPECIAL_CHARACTER;
}
